### ISSUE TITLE
Confirmation step for checking PATH gives precedence to $HOME/.local/bin

### ISSUE THREAD

**Issue by richardcane** [zee-ahmed/kubemngr#19]
**Is your feature request related to a problem? Please describe.**
The `use` command currently doesn't work because we can't replace the `kubectl` binary in `usr/local/bin` due to permissions. 

The 'standard' way around this (see [tfutils/tfenv](https://github.com/tfutils/tfenv)) is to have the user modify the PATH to include a bin folder that we do have permission to change, but it would be nice to add some sort of check on the bin folder precedence in the PATH like brew has, and then either echo some commands the user can copy pasta, or just do it ourselves with a y/n.

**Describe the solution you'd like**
Ideally, whenever I run a `kubemngr` command, it will check my bin folder precedence and suggest a modification to my PATH that I can either accept or reject. If I reject it, I should understand that without the change in PATH, `kubectl` will continue to be executed from `usr/local/bin`. 

**Describe alternatives you've considered**
The problem is in bin folder precedence in the PATH. `sudo` could be used to change the `kubectl` binary in `/usr/local/bin` but this seems overly heavy handed. There might also be an alternative option as a result of using brew to install kubemngr, but it would be preferable not to rely on a third party application.

If anyone reading this issue has any better ideas, please leave a comment!

**Comment by simplyzee** [comment]
Thanks @richardcane for the issue. I agree that that the CLI tool should have some input to let the user know if they haven't exported the `$PATH` and wish to do so from the CLI.

Currently, it's noted in the README before installation to export the `$PATH` but I'm all for automating this / prompting the user for better user experience.

**Comment by richardcane** [comment]
Apparently modifying people's environment variables is bad form so suggested modifications will do for now 😁
